export class ProductsService {
    products = [
        {
            id: 1,
            name: 'Adidas Grey T-shirt',
            price: 12.5,
            gender: 'men',
            category: 'tshirts',
            image1: 'assets/products/men/tshirts/adidas_grey_1.png',
            image2: 'assets/products/men/tshirts/adidas_grey_2.png',
            src: '',
        },
        {
            id: 2,
            name: "Adidas Red T-shirt",
            price: 12,
            gender: "men",
            category: "tshirts",
            image1: "assets/products/men/tshirts/adidas_red_1.png",
            image2: "assets/products/men/tshirts/adidas_red_2.png",
            src: '',
        },
        {
            id: 3,
            name: "Adidas Long Sleeve T-shirt",
            price: 14.9,
            gender: "men",
            category: "tshirts",
            image1: "assets/products/men/tshirts/adidas_long_sleeve_1.png",
            image2: "assets/products/men/tshirts/adidas_long_sleeve_2.png",
            src: '',
        },
        {
            id: 4,
            name: "Nike Air Black T-shirt",
            price: 13.9,
            gender: "men",
            category: "tshirts",
            image1: "assets/products/men/tshirts/nike_air_black_1.png",
            image2: "assets/products/men/tshirts/nike_air_black_2.png",
            src: '',
        },
        {
            id: 5,
            name: "Nike Air Jordan Grey T-shirt",
            price: 15.5,
            gender: "men",
            category: "tshirts",
            image1: "assets/products/men/tshirts/air_jordan_grey_1.png",
            image2: "assets/products/men/tshirts/air_jordan_grey_2.png",
            src: '',
        },
        {
            id: 6,
            name: "Nike Long Sleeve T-shirt",
            price: 17,
            gender: "men",
            category: "tshirts",
            image1: "assets/products/men/tshirts/nike_long_sleeve_1.png",
            image2: "assets/products/men/tshirts/nike_long_sleeve_2.png",
            src: '',
        },{
            id: 7,
            name: 'Adidas Essential Big Logo Sweatshirt',
            price: 52.5,
            gender: 'men',
            category: 'sweaters',
            image1: 'assets/products/men/sweaters/adidas_ess_big_logo_1.png',
            image2: 'assets/products/men/sweaters/adidas_ess_big_logo_2.png',
            src: '',
        },
        {
            id: 8,
            name: "Adidas Essential Hoodie",
            price: 61,
            gender: "men",
            category: "sweaters",
            image1: "assets/products/men/sweaters/adidas_essential_hoodie_1.png",
            image2: "assets/products/men/sweaters/adidas_essential_hoodie_2.png",
            src: '',
        },
        {
            id: 9,
            name: "Adidas Zipped Sweater",
            price: 54.9,
            gender: "men",
            category: "sweaters",
            image1: "assets/products/men/sweaters/adidas_zipped_1.png",
            image2: "assets/products/men/sweaters/adidas_zipped_2.png",
            src: '',
        },
        {
            id: 10,
            name: "Nike Air Big Logo Sweatshirt",
            price: 53.9,
            gender: "men",
            category: "sweaters",
            image1: "assets/products/men/sweaters/nike_air_big_logo_1.png",
            image2: "assets/products/men/sweaters/nike_air_big_logo_2.png",
            src: '',
        },
        {
            id: 11,
            name: "Nike Air Jordan Hoodie",
            price: 65.5,
            gender: "men",
            category: "sweaters",
            image1: "assets/products/men/sweaters/nike_air_jordan_1.png",
            image2: "assets/products/men/sweaters/nike_air_jordan_2.png",
            src: '',
        },
        {
            id: 12,
            name: "Nike Zipped Sweater",
            price: 57,
            gender: "men",
            category: "sweaters",
            image1: "assets/products/men/sweaters/nike_zipped_1.png",
            image2: "assets/products/men/sweaters/nike_zipped_2.png",
            src: '',
        },

        {
            id: 13,
            name: 'Adidas Duramo Running Shoes',
            price: 46.5,
            gender: 'men',
            category: 'sneakers',
            image1: 'assets/products/men/sneakers/adidas_duramo_1.png',
            image2: 'assets/products/men/sneakers/adidas_duramo_2.png',
            src: '',
        },
        {
            id: 14,
            name: "Adidas FluidFlow Running Shoes",
            price: 39,
            gender: "men",
            category: "sneakers",
            image1: "assets/products/men/sneakers/adidas_fluidflow_1.png",
            image2: "assets/products/men/sneakers/adidas_fluidflow_2.png",
            src: '',
        },
        {
            id: 15,
            name: "Adidas Response Running Shoes",
            price: 41.9,
            gender: "men",
            category: "sneakers",
            image1: "assets/products/men/sneakers/adidas_response_1.png",
            image2: "assets/products/men/sneakers/adidas_response_2.png",
            src: '',
        },
        {
            id: 16,
            name: "Adidas Ultra 4D Running Shoes",
            price: 33.5,
            gender: "men",
            category: "sneakers",
            image1: "assets/products/men/sneakers/adidas_ultra_4d_1.png",
            image2: "assets/products/men/sneakers/adidas_ultra_4d_2.png",
            src: '',
        },
        {
            id: 17,
            name: "Nike Air Jordan Basketball Shoes",
            price: 65.7,
            gender: "men",
            category: "sneakers",
            image1: "assets/products/men/sneakers/nike_air_jordan_1.png",
            image2: "assets/products/men/sneakers/nike_air_jordan_2.png",
            src: '',
        },
        {
            id: 18,
            name: "Nike Air Zoom Running Shoes",
            price: 47,
            gender: "men",
            category: "sneakers",
            image1: "assets/products/men/sneakers/nike_air_zoom_1.png",
            image2: "assets/products/men/sneakers/nike_air_zoom_2.png",
            src: '',
        },
        {
            id: 19,
            name: "Nike Lebron James Basketball Shoes",
            price: 63.5,
            gender: "men",
            category: "sneakers",
            image1: "assets/products/men/sneakers/nike_lebron_1.png",
            image2: "assets/products/men/sneakers/nike_lebron_2.png",
            src: '',
        },
        {
            id: 20,
            name: "Nike Pegasus Running Shoes",
            price: 42.3,
            gender: "men",
            category: "sneakers",
            image1: "assets/products/men/sneakers/nike_pegasus_1.png",
            image2: "assets/products/men/sneakers/nike_pegasus_2.png",
            src: '',
        },
        {
            id: 21,
            name: "Nike React Running Shoes",
            price: 41,
            gender: "men",
            category: "sneakers",
            image1: "assets/products/men/sneakers/nike_react_1.png",
            image2: "assets/products/men/sneakers/nike_react_2.png",
            src: '',
        },
    ];
}