export class ProductsService {
    products = [
        {
            id: 1,
            name: 'Adidas Grey T-shirt',
            price: 12.5,
            gender: 'men',
            category: 'tshirts',
            image1: 'assets/products/men/tshirts/adidas_grey_1.png',
            image2: 'assets/products/men/tshirts/adidas_grey_2.png',
            src: '',
        },
        {
            id: 2,
            name: "Adidas Red T-shirt",
            price: 12,
            gender: "men",
            category: "tshirts",
            image1: "assets/products/men/tshirts/adidas_red_1.png",
            image2: "assets/products/men/tshirts/adidas_red_2.png",
            src: '',
        },
        {
            id: 3,
            name: "Adidas Long Sleeve T-shirt",
            price: 14.9,
            gender: "men",
            category: "tshirts",
            image1: "assets/products/men/tshirts/adidas_long_sleeve_1.png",
            image2: "assets/products/men/tshirts/adidas_long_sleeve_2.png",
            src: '',
        },
        {
            id: 4,
            name: "Nike Air Black T-shirt",
            price: 13.9,
            gender: "men",
            category: "tshirts",
            image1: "assets/products/men/tshirts/nike_air_black_1.png",
            image2: "assets/products/men/tshirts/nike_air_black_2.png",
            src: '',
        },
        {
            id: 5,
            name: "Nike Air Jordan Grey T-shirt",
            price: 15.5,
            gender: "men",
            category: "tshirts",
            image1: "assets/products/men/tshirts/air_jordan_grey_1.png",
            image2: "assets/products/men/tshirts/air_jordan_grey_2.png",
            src: '',
        },
        {
            id: 6,
            name: "Nike Long Sleeve T-shirt",
            price: 17,
            gender: "men",
            category: "tshirts",
            image1: "assets/products/men/tshirts/nike_long_sleeve_1.png",
            image2: "assets/products/men/tshirts/nike_long_sleeve_2.png",
            src: '',
        }
    ];
}